project:
  type: website
  output-dir: docs

website:
  title: "Anika's ML Blogs"
  description: "5 different blogs covering various ML topics."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/anika-thatavarthy/
format:
  html:
    theme: minty
    css: styles.css



